/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as NettoyageDeBureauxRouteImport } from './routes/nettoyage-de-bureaux'
import { Route as NettoyageIleDeFranceRouteImport } from './routes/nettoyage-ile-de-france'
import { Route as NettoyagePantinRouteImport } from './routes/nettoyage-pantin'
import { Route as NettoyageParisRouteImport } from './routes/nettoyage-paris'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAujourdhuiRouteImport } from './routes/_authenticated/app.aujourdhui'
import { Route as AuthenticatedAppLinkedinRouteImport } from './routes/_authenticated/app.linkedin'
import { Route as AuthenticatedAppPipelineRouteImport } from './routes/_authenticated/app.pipeline'
import { Route as AuthenticatedAppProspectionRouteImport } from './routes/_authenticated/app.prospection'
import { Route as AuthenticatedAppTarifsRouteImport } from './routes/_authenticated/app.tarifs'
import { Route as AuthenticatedAppDemandesIndexRouteImport } from './routes/_authenticated/app.demandes.index'
import { Route as AuthenticatedAppDemandesIdRouteImport } from './routes/_authenticated/app.demandes.$id'
import { Route as ApiPublicHooksAutomatisationQuotidienneRouteImport } from './routes/api/public/hooks/automatisation-quotidienne'
import { Route as ApiPublicHooksB2bLeadRouteImport } from './routes/api/public/hooks/b2b-lead'
import { Route as ApiPublicHooksProspectionQuotidienneRouteImport } from './routes/api/public/hooks/prospection-quotidienne'
import { Route as ApiPublicHooksQuoteRequestRouteImport } from './routes/api/public/hooks/quote-request'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageDeBureauxRoute = NettoyageDeBureauxRouteImport.update({
  id: '/nettoyage-de-bureaux',
  path: '/nettoyage-de-bureaux',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageIleDeFranceRoute = NettoyageIleDeFranceRouteImport.update({
  id: '/nettoyage-ile-de-france',
  path: '/nettoyage-ile-de-france',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyagePantinRoute = NettoyagePantinRouteImport.update({
  id: '/nettoyage-pantin',
  path: '/nettoyage-pantin',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageParisRoute = NettoyageParisRouteImport.update({
  id: '/nettoyage-paris',
  path: '/nettoyage-paris',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAujourdhuiRoute =
  AuthenticatedAppAujourdhuiRouteImport.update({
    id: '/aujourdhui',
    path: '/aujourdhui',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLinkedinRoute =
  AuthenticatedAppLinkedinRouteImport.update({
    id: '/linkedin',
    path: '/linkedin',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPipelineRoute =
  AuthenticatedAppPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProspectionRoute =
  AuthenticatedAppProspectionRouteImport.update({
    id: '/prospection',
    path: '/prospection',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTarifsRoute = AuthenticatedAppTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDemandesIndexRoute =
  AuthenticatedAppDemandesIndexRouteImport.update({
    id: '/demandes/',
    path: '/demandes/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDemandesIdRoute =
  AuthenticatedAppDemandesIdRouteImport.update({
    id: '/demandes/$id',
    path: '/demandes/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicHooksAutomatisationQuotidienneRoute =
  ApiPublicHooksAutomatisationQuotidienneRouteImport.update({
    id: '/api/public/hooks/automatisation-quotidienne',
    path: '/api/public/hooks/automatisation-quotidienne',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksB2bLeadRoute = ApiPublicHooksB2bLeadRouteImport.update({
  id: '/api/public/hooks/b2b-lead',
  path: '/api/public/hooks/b2b-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProspectionQuotidienneRoute =
  ApiPublicHooksProspectionQuotidienneRouteImport.update({
    id: '/api/public/hooks/prospection-quotidienne',
    path: '/api/public/hooks/prospection-quotidienne',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksQuoteRequestRoute =
  ApiPublicHooksQuoteRequestRouteImport.update({
    id: '/api/public/hooks/quote-request',
    path: '/api/public/hooks/quote-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/merci': typeof MerciRoute
  '/nettoyage-de-bureaux': typeof NettoyageDeBureauxRoute
  '/nettoyage-ile-de-france': typeof NettoyageIleDeFranceRoute
  '/nettoyage-pantin': typeof NettoyagePantinRoute
  '/nettoyage-paris': typeof NettoyageParisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/aujourdhui': typeof AuthenticatedAppAujourdhuiRoute
  '/app/linkedin': typeof AuthenticatedAppLinkedinRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/prospection': typeof AuthenticatedAppProspectionRoute
  '/app/tarifs': typeof AuthenticatedAppTarifsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/demandes/$id': typeof AuthenticatedAppDemandesIdRoute
  '/api/public/hooks/automatisation-quotidienne': typeof ApiPublicHooksAutomatisationQuotidienneRoute
  '/api/public/hooks/b2b-lead': typeof ApiPublicHooksB2bLeadRoute
  '/api/public/hooks/prospection-quotidienne': typeof ApiPublicHooksProspectionQuotidienneRoute
  '/api/public/hooks/quote-request': typeof ApiPublicHooksQuoteRequestRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/app/demandes/': typeof AuthenticatedAppDemandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/merci': typeof MerciRoute
  '/nettoyage-de-bureaux': typeof NettoyageDeBureauxRoute
  '/nettoyage-ile-de-france': typeof NettoyageIleDeFranceRoute
  '/nettoyage-pantin': typeof NettoyagePantinRoute
  '/nettoyage-paris': typeof NettoyageParisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/aujourdhui': typeof AuthenticatedAppAujourdhuiRoute
  '/app/linkedin': typeof AuthenticatedAppLinkedinRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/prospection': typeof AuthenticatedAppProspectionRoute
  '/app/tarifs': typeof AuthenticatedAppTarifsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/demandes/$id': typeof AuthenticatedAppDemandesIdRoute
  '/api/public/hooks/automatisation-quotidienne': typeof ApiPublicHooksAutomatisationQuotidienneRoute
  '/api/public/hooks/b2b-lead': typeof ApiPublicHooksB2bLeadRoute
  '/api/public/hooks/prospection-quotidienne': typeof ApiPublicHooksProspectionQuotidienneRoute
  '/api/public/hooks/quote-request': typeof ApiPublicHooksQuoteRequestRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/app/demandes': typeof AuthenticatedAppDemandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/merci': typeof MerciRoute
  '/nettoyage-de-bureaux': typeof NettoyageDeBureauxRoute
  '/nettoyage-ile-de-france': typeof NettoyageIleDeFranceRoute
  '/nettoyage-pantin': typeof NettoyagePantinRoute
  '/nettoyage-paris': typeof NettoyageParisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/aujourdhui': typeof AuthenticatedAppAujourdhuiRoute
  '/_authenticated/app/linkedin': typeof AuthenticatedAppLinkedinRoute
  '/_authenticated/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/_authenticated/app/prospection': typeof AuthenticatedAppProspectionRoute
  '/_authenticated/app/tarifs': typeof AuthenticatedAppTarifsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/demandes/$id': typeof AuthenticatedAppDemandesIdRoute
  '/api/public/hooks/automatisation-quotidienne': typeof ApiPublicHooksAutomatisationQuotidienneRoute
  '/api/public/hooks/b2b-lead': typeof ApiPublicHooksB2bLeadRoute
  '/api/public/hooks/prospection-quotidienne': typeof ApiPublicHooksProspectionQuotidienneRoute
  '/api/public/hooks/quote-request': typeof ApiPublicHooksQuoteRequestRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/app/demandes/': typeof AuthenticatedAppDemandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/merci'
    | '/nettoyage-de-bureaux'
    | '/nettoyage-ile-de-france'
    | '/nettoyage-pantin'
    | '/nettoyage-paris'
    | '/reset-password'
    | '/app'
    | '/app/aujourdhui'
    | '/app/linkedin'
    | '/app/pipeline'
    | '/app/prospection'
    | '/app/tarifs'
    | '/app/'
    | '/app/demandes/$id'
    | '/api/public/hooks/automatisation-quotidienne'
    | '/api/public/hooks/b2b-lead'
    | '/api/public/hooks/prospection-quotidienne'
    | '/api/public/hooks/quote-request'
    | '/lovable/email/transactional/preview'
    | '/app/demandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/merci'
    | '/nettoyage-de-bureaux'
    | '/nettoyage-ile-de-france'
    | '/nettoyage-pantin'
    | '/nettoyage-paris'
    | '/reset-password'
    | '/app/aujourdhui'
    | '/app/linkedin'
    | '/app/pipeline'
    | '/app/prospection'
    | '/app/tarifs'
    | '/app'
    | '/app/demandes/$id'
    | '/api/public/hooks/automatisation-quotidienne'
    | '/api/public/hooks/b2b-lead'
    | '/api/public/hooks/prospection-quotidienne'
    | '/api/public/hooks/quote-request'
    | '/lovable/email/transactional/preview'
    | '/app/demandes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/merci'
    | '/nettoyage-de-bureaux'
    | '/nettoyage-ile-de-france'
    | '/nettoyage-pantin'
    | '/nettoyage-paris'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/aujourdhui'
    | '/_authenticated/app/linkedin'
    | '/_authenticated/app/pipeline'
    | '/_authenticated/app/prospection'
    | '/_authenticated/app/tarifs'
    | '/_authenticated/app/'
    | '/_authenticated/app/demandes/$id'
    | '/api/public/hooks/automatisation-quotidienne'
    | '/api/public/hooks/b2b-lead'
    | '/api/public/hooks/prospection-quotidienne'
    | '/api/public/hooks/quote-request'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/app/demandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MerciRoute: typeof MerciRoute
  NettoyageDeBureauxRoute: typeof NettoyageDeBureauxRoute
  NettoyageIleDeFranceRoute: typeof NettoyageIleDeFranceRoute
  NettoyagePantinRoute: typeof NettoyagePantinRoute
  NettoyageParisRoute: typeof NettoyageParisRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksAutomatisationQuotidienneRoute: typeof ApiPublicHooksAutomatisationQuotidienneRoute
  ApiPublicHooksB2bLeadRoute: typeof ApiPublicHooksB2bLeadRoute
  ApiPublicHooksProspectionQuotidienneRoute: typeof ApiPublicHooksProspectionQuotidienneRoute
  ApiPublicHooksQuoteRequestRoute: typeof ApiPublicHooksQuoteRequestRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-de-bureaux': {
      id: '/nettoyage-de-bureaux'
      path: '/nettoyage-de-bureaux'
      fullPath: '/nettoyage-de-bureaux'
      preLoaderRoute: typeof NettoyageDeBureauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-ile-de-france': {
      id: '/nettoyage-ile-de-france'
      path: '/nettoyage-ile-de-france'
      fullPath: '/nettoyage-ile-de-france'
      preLoaderRoute: typeof NettoyageIleDeFranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-pantin': {
      id: '/nettoyage-pantin'
      path: '/nettoyage-pantin'
      fullPath: '/nettoyage-pantin'
      preLoaderRoute: typeof NettoyagePantinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-paris': {
      id: '/nettoyage-paris'
      path: '/nettoyage-paris'
      fullPath: '/nettoyage-paris'
      preLoaderRoute: typeof NettoyageParisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/aujourdhui': {
      id: '/_authenticated/app/aujourdhui'
      path: '/aujourdhui'
      fullPath: '/app/aujourdhui'
      preLoaderRoute: typeof AuthenticatedAppAujourdhuiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/linkedin': {
      id: '/_authenticated/app/linkedin'
      path: '/linkedin'
      fullPath: '/app/linkedin'
      preLoaderRoute: typeof AuthenticatedAppLinkedinRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pipeline': {
      id: '/_authenticated/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AuthenticatedAppPipelineRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prospection': {
      id: '/_authenticated/app/prospection'
      path: '/prospection'
      fullPath: '/app/prospection'
      preLoaderRoute: typeof AuthenticatedAppProspectionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tarifs': {
      id: '/_authenticated/app/tarifs'
      path: '/tarifs'
      fullPath: '/app/tarifs'
      preLoaderRoute: typeof AuthenticatedAppTarifsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/demandes/': {
      id: '/_authenticated/app/demandes/'
      path: '/demandes'
      fullPath: '/app/demandes/'
      preLoaderRoute: typeof AuthenticatedAppDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/demandes/$id': {
      id: '/_authenticated/app/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/app/demandes/$id'
      preLoaderRoute: typeof AuthenticatedAppDemandesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/automatisation-quotidienne': {
      id: '/api/public/hooks/automatisation-quotidienne'
      path: '/api/public/hooks/automatisation-quotidienne'
      fullPath: '/api/public/hooks/automatisation-quotidienne'
      preLoaderRoute: typeof ApiPublicHooksAutomatisationQuotidienneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/b2b-lead': {
      id: '/api/public/hooks/b2b-lead'
      path: '/api/public/hooks/b2b-lead'
      fullPath: '/api/public/hooks/b2b-lead'
      preLoaderRoute: typeof ApiPublicHooksB2bLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/prospection-quotidienne': {
      id: '/api/public/hooks/prospection-quotidienne'
      path: '/api/public/hooks/prospection-quotidienne'
      fullPath: '/api/public/hooks/prospection-quotidienne'
      preLoaderRoute: typeof ApiPublicHooksProspectionQuotidienneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/quote-request': {
      id: '/api/public/hooks/quote-request'
      path: '/api/public/hooks/quote-request'
      fullPath: '/api/public/hooks/quote-request'
      preLoaderRoute: typeof ApiPublicHooksQuoteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAujourdhuiRoute: typeof AuthenticatedAppAujourdhuiRoute
  AuthenticatedAppLinkedinRoute: typeof AuthenticatedAppLinkedinRoute
  AuthenticatedAppPipelineRoute: typeof AuthenticatedAppPipelineRoute
  AuthenticatedAppProspectionRoute: typeof AuthenticatedAppProspectionRoute
  AuthenticatedAppTarifsRoute: typeof AuthenticatedAppTarifsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppDemandesIdRoute: typeof AuthenticatedAppDemandesIdRoute
  AuthenticatedAppDemandesIndexRoute: typeof AuthenticatedAppDemandesIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAujourdhuiRoute: AuthenticatedAppAujourdhuiRoute,
  AuthenticatedAppLinkedinRoute: AuthenticatedAppLinkedinRoute,
  AuthenticatedAppPipelineRoute: AuthenticatedAppPipelineRoute,
  AuthenticatedAppProspectionRoute: AuthenticatedAppProspectionRoute,
  AuthenticatedAppTarifsRoute: AuthenticatedAppTarifsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppDemandesIdRoute: AuthenticatedAppDemandesIdRoute,
  AuthenticatedAppDemandesIndexRoute: AuthenticatedAppDemandesIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MerciRoute: MerciRoute,
  NettoyageDeBureauxRoute: NettoyageDeBureauxRoute,
  NettoyageIleDeFranceRoute: NettoyageIleDeFranceRoute,
  NettoyagePantinRoute: NettoyagePantinRoute,
  NettoyageParisRoute: NettoyageParisRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksAutomatisationQuotidienneRoute:
    ApiPublicHooksAutomatisationQuotidienneRoute,
  ApiPublicHooksB2bLeadRoute: ApiPublicHooksB2bLeadRoute,
  ApiPublicHooksProspectionQuotidienneRoute:
    ApiPublicHooksProspectionQuotidienneRoute,
  ApiPublicHooksQuoteRequestRoute: ApiPublicHooksQuoteRequestRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
