/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ZonesIndexRouteImport } from './routes/zones.index'
import { Route as ZonesSlugRouteImport } from './routes/zones.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesIndexRoute = ZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesSlugRoute = ZonesSlugRouteImport.update({
  id: '/zones/$slug',
  path: '/zones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/zones/': typeof ZonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/zones': typeof ZonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/zones/': typeof ZonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/services/$slug' | '/zones/$slug' | '/services/' | '/zones/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/services/$slug' | '/zones/$slug' | '/services' | '/zones'
  id:
    | '__root__'
    | '/'
    | '/services/$slug'
    | '/zones/$slug'
    | '/services/'
    | '/zones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ZonesSlugRoute: typeof ZonesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ZonesIndexRoute: typeof ZonesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/': {
      id: '/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof ZonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/$slug': {
      id: '/zones/$slug'
      path: '/zones/$slug'
      fullPath: '/zones/$slug'
      preLoaderRoute: typeof ZonesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ZonesSlugRoute: ZonesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ZonesIndexRoute: ZonesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
