/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ZonesIndexRouteImport } from './routes/zones.index'
import { Route as ZonesSlugRouteImport } from './routes/zones.$slug'
import { Route as ApiPublicDevisRouteImport } from './routes/api/public/devis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesIndexRoute = ZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesSlugRoute = ZonesSlugRouteImport.update({
  id: '/zones/$slug',
  path: '/zones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevisRoute = ApiPublicDevisRouteImport.update({
  id: '/api/public/devis',
  path: '/api/public/devis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/zones/': typeof ZonesIndexRoute
  '/api/public/devis': typeof ApiPublicDevisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/zones': typeof ZonesIndexRoute
  '/api/public/devis': typeof ApiPublicDevisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/zones/': typeof ZonesIndexRoute
  '/api/public/devis': typeof ApiPublicDevisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/sitemap.xml'
    | '/tarifs'
    | '/services/$slug'
    | '/zones/$slug'
    | '/services/'
    | '/zones/'
    | '/api/public/devis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/sitemap.xml'
    | '/tarifs'
    | '/services/$slug'
    | '/zones/$slug'
    | '/services'
    | '/zones'
    | '/api/public/devis'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/sitemap.xml'
    | '/tarifs'
    | '/services/$slug'
    | '/zones/$slug'
    | '/services/'
    | '/zones/'
    | '/api/public/devis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ZonesSlugRoute: typeof ZonesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ZonesIndexRoute: typeof ZonesIndexRoute
  ApiPublicDevisRoute: typeof ApiPublicDevisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/': {
      id: '/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof ZonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/$slug': {
      id: '/zones/$slug'
      path: '/zones/$slug'
      fullPath: '/zones/$slug'
      preLoaderRoute: typeof ZonesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devis': {
      id: '/api/public/devis'
      path: '/api/public/devis'
      fullPath: '/api/public/devis'
      preLoaderRoute: typeof ApiPublicDevisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ZonesSlugRoute: ZonesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ZonesIndexRoute: ZonesIndexRoute,
  ApiPublicDevisRoute: ApiPublicDevisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
