/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ZonesIndexRouteImport } from './routes/zones.index'
import { Route as ZonesSlugRouteImport } from './routes/zones.$slug'
import { Route as ApiPublicAvisRouteImport } from './routes/api/public/avis'
import { Route as ApiPublicDevisRouteImport } from './routes/api/public/devis'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesIndexRoute = ZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesSlugRoute = ZonesSlugRouteImport.update({
  id: '/zones/$slug',
  path: '/zones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvisRoute = ApiPublicAvisRouteImport.update({
  id: '/api/public/avis',
  path: '/api/public/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevisRoute = ApiPublicDevisRouteImport.update({
  id: '/api/public/devis',
  path: '/api/public/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/zones/': typeof ZonesIndexRoute
  '/api/public/avis': typeof ApiPublicAvisRoute
  '/api/public/devis': typeof ApiPublicDevisRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/zones': typeof ZonesIndexRoute
  '/api/public/avis': typeof ApiPublicAvisRoute
  '/api/public/devis': typeof ApiPublicDevisRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/zones/': typeof ZonesIndexRoute
  '/api/public/avis': typeof ApiPublicAvisRoute
  '/api/public/devis': typeof ApiPublicDevisRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/avis'
    | '/connexion'
    | '/contact'
    | '/devis'
    | '/faq'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/tarifs'
    | '/admin'
    | '/services/$slug'
    | '/zones/$slug'
    | '/services/'
    | '/zones/'
    | '/api/public/avis'
    | '/api/public/devis'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/avis'
    | '/connexion'
    | '/contact'
    | '/devis'
    | '/faq'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/tarifs'
    | '/admin'
    | '/services/$slug'
    | '/zones/$slug'
    | '/services'
    | '/zones'
    | '/api/public/avis'
    | '/api/public/devis'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/avis'
    | '/connexion'
    | '/contact'
    | '/devis'
    | '/faq'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/sitemap.xml'
    | '/tarifs'
    | '/_authenticated/admin'
    | '/services/$slug'
    | '/zones/$slug'
    | '/services/'
    | '/zones/'
    | '/api/public/avis'
    | '/api/public/devis'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AvisRoute: typeof AvisRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ZonesSlugRoute: typeof ZonesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ZonesIndexRoute: typeof ZonesIndexRoute
  ApiPublicAvisRoute: typeof ApiPublicAvisRoute
  ApiPublicDevisRoute: typeof ApiPublicDevisRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/': {
      id: '/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof ZonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/$slug': {
      id: '/zones/$slug'
      path: '/zones/$slug'
      fullPath: '/zones/$slug'
      preLoaderRoute: typeof ZonesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avis': {
      id: '/api/public/avis'
      path: '/api/public/avis'
      fullPath: '/api/public/avis'
      preLoaderRoute: typeof ApiPublicAvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devis': {
      id: '/api/public/devis'
      path: '/api/public/devis'
      fullPath: '/api/public/devis'
      preLoaderRoute: typeof ApiPublicDevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AvisRoute: AvisRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ZonesSlugRoute: ZonesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ZonesIndexRoute: ZonesIndexRoute,
  ApiPublicAvisRoute: ApiPublicAvisRoute,
  ApiPublicDevisRoute: ApiPublicDevisRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
